proxies:
  - name: "SS-SR-Server"
    type: ss
    server: '43.131.243.142'    
    port: 8388              
    cipher: aes-128-gcm  
    password: "oRlhsMk5nlKi"   
    udp: true                  

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "SS-SR-Server"        

rules:
  - DOMAIN-SUFFIX,google.com,PROXY    
  - DOMAIN-SUFFIX,youtube.com,PROXY  
  - GEOIP,CN,DIRECT                  
  - MATCH,PROXY        
